# Generated by Django 2.2.16 on 2022-10-30 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20221001_2243'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={
                'verbose_name': 'группа',
                'verbose_name_plural': 'группы',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'ordering': ('-pub_date',),
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(
                help_text='описание группы', verbose_name='описание'
            ),
        ),
        migrations.AlterField(
            model_name='group',
            name='slug',
            field=models.SlugField(
                help_text='текстовый идентификатор страницы',
                unique=True,
                verbose_name='текстовый идентификатор страницы',
            ),
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(
                help_text='название группы',
                max_length=200,
                verbose_name='название',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                help_text='укажите автора поста',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(
                blank=True,
                help_text='группа, к которой будет относиться пост',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='posts',
                to='posts.Group',
                verbose_name='группа',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='дата публикации поста',
                verbose_name='дата публикации',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(
                help_text='введите текст поста', verbose_name='текст поста'
            ),
        ),
    ]
