# Generated by Django 2.2.16 on 2022-10-30 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20221030_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='добавьте изображение',
                upload_to='posts/',
                verbose_name='изображение',
            ),
        ),
    ]
