# Generated by Django 2.2.16 on 2022-10-30 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0009_auto_20221030_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        help_text='введите текст комментария',
                        verbose_name='текст комментария',
                    ),
                ),
                (
                    'created',
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text='дата создания комментария',
                        verbose_name='дата создания',
                    ),
                ),
                (
                    'author',
                    models.ForeignKey(
                        help_text='укажите автора комментария',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='автор',
                    ),
                ),
                (
                    'post',
                    models.ForeignKey(
                        help_text='напишите комментарий',
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='comments',
                        to='posts.Post',
                        verbose_name='комментарий',
                    ),
                ),
            ],
            options={
                'ordering': ('-created',),
                'default_related_name': 'comments',
            },
        ),
    ]
