# Generated by Django 2.2.16 on 2022-10-30 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'ordering': ('-created',),
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='дата публикации поста',
                verbose_name='Дата создания',
            ),
        ),
    ]
