# Generated by Django 2.2.16 on 2022-10-30 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20221031_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                help_text='дата создания',
                verbose_name='дата создания',
            ),
        ),
    ]
