# Generated by Django 2.2.16 on 2022-11-04 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20221104_2304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={
                'default_related_name': 'comments',
                'verbose_name': 'комментарий',
                'verbose_name_plural': 'комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={
                'default_related_name': 'posts',
                'verbose_name': 'пост',
                'verbose_name_plural': 'посты',
            },
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='дата создания',
                verbose_name='дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(
                help_text='введите текст', verbose_name='текст'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(
                help_text='укажите автора',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='posts',
                to=settings.AUTH_USER_MODEL,
                verbose_name='автор',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(
                auto_now_add=True,
                db_index=True,
                help_text='дата создания',
                verbose_name='дата создания',
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(
                help_text='введите текст', verbose_name='текст'
            ),
        ),
    ]
